# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE_TYPE: "performance" (for perf tests) and "gva" (for linux machines connected to DB services)


RUN_ACTIVITY:
#  - run-db-unit-tests-mysql56
#  - run-db-unit-tests-mssql2012
#  - run-db-unit-tests-mssql2014
#  - run-db-unit-tests-oracle11g
#  - run-db-unit-tests-oracle12c
#  - run-db-unit-tests-postgresql93
#  - run-db-integration-tests-mssql2014-Category1
#  - run-db-integration-tests-mssql2014-Category2
#  - run-db-integration-tests-mssql2014-Category3
#  - run-db-integration-tests-mssql2014-Category4
#  - run-db-integration-tests-mssql2014-Category5
#  - run-upgrade-tests-mssql2014
  # this category runs on MS Windows
  - run-it-released-plugins
#  - run-perf-tests

exclude:
  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2012
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2014
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-oracle11g
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-oracle12c
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category5
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-mssql2014
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-it-released-plugins
    SLAVE_TYPE: performance

  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: dblinux

  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-mssql2012
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-mssql2014
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-oracle11g
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-oracle12c
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-postgresql93
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category1
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category2
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category3
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category4
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category5
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-upgrade-tests-mssql2014
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: windows
